/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_regex_include_h__
#define _mulle_regex_include_h__

// You can tweak the following #include with these commands.
// (Use DA632302-CC77-41E3-A7C2-16F226549339 instead of mulle-utf if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-utf no-header`
//    rename:             `mulle-sde dependency|library set mulle-utf include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-utf <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-utf [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-utf [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-utf [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-utf no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-utf/mulle-utf.h>   // mulle-utf

#endif
