/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_regex_include_h__
#define _mulle_regex_include_h__

# include <mulle-c11/mulle-c11.h>   // mulle-c11

# include <mulle-thread/mulle-thread.h>   // mulle-thread

# include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

# include <mulle-aba/mulle-aba.h>   // mulle-aba

# include <mulle-concurrent/mulle-concurrent.h>   // mulle-concurrent

# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

# include <mulle-container/mulle-container.h>   // mulle-container

# include <mulle-utf/mulle-utf.h>   // mulle-utf

# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

# include <mulle-sprintf/mulle-sprintf.h>   // mulle-sprintf

#endif
