/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_regex_include_h__
#define _mulle_regex_include_h__

// How to tweak the following mulle-utf #include
//    remove:        `mulle-sourcetree mark mulle-utf no-header`
//    rename:        `mulle-sourcetree mark mulle-utf set include whatever.h`
//    make private:  `mulle-sourcetree mark mulle-utf no-public`
//    make public:   `mulle-sourcetree mark mulle-utf public`
//    make optional: `mulle-sourcetree mark mulle-utf no-require`
//    remove for os: `mulle-sourcetree mark mulle-utf no-os-<osname>`
# include <mulle-utf/mulle-utf.h>   // mulle-utf

#endif
